var annotated_dup =
[
    [ "APP_DATA", "struct_a_p_p___d_a_t_a.html", "struct_a_p_p___d_a_t_a" ],
    [ "APP_DISP_DATA", "struct_a_p_p___d_i_s_p___d_a_t_a.html", "struct_a_p_p___d_i_s_p___d_a_t_a" ],
    [ "APP_INPUTS_DATA", "struct_a_p_p___i_n_p_u_t_s___d_a_t_a.html", "struct_a_p_p___i_n_p_u_t_s___d_a_t_a" ],
    [ "APP_REG_DATA", "struct_a_p_p___r_e_g___d_a_t_a.html", "struct_a_p_p___r_e_g___d_a_t_a" ],
    [ "app_task_ctrl_t", "structapp__task__ctrl__t.html", "structapp__task__ctrl__t" ],
    [ "APP_TOUCH_DATA", "struct_a_p_p___t_o_u_c_h___d_a_t_a.html", "struct_a_p_p___t_o_u_c_h___d_a_t_a" ],
    [ "ConfInSwitchs", "struct_conf_in_switchs.html", "struct_conf_in_switchs" ],
    [ "MODULE_SLOT_DATA", "struct_m_o_d_u_l_e___s_l_o_t___d_a_t_a.html", "struct_m_o_d_u_l_e___s_l_o_t___d_a_t_a" ],
    [ "S_AT42QT2120", "struct_s___a_t42_q_t2120.html", "struct_s___a_t42_q_t2120" ],
    [ "S_OBJECT", "struct_s___o_b_j_e_c_t.html", "struct_s___o_b_j_e_c_t" ],
    [ "S_WINDOW", "struct_s___w_i_n_d_o_w.html", "struct_s___w_i_n_d_o_w" ],
    [ "SERIAL_REG_DATA", "union_s_e_r_i_a_l___r_e_g___d_a_t_a.html", "union_s_e_r_i_a_l___r_e_g___d_a_t_a" ],
    [ "SwithcConfig", "struct_swithc_config.html", "struct_swithc_config" ],
    [ "T_DISPLAY", "struct_t___d_i_s_p_l_a_y.html", "struct_t___d_i_s_p_l_a_y" ],
    [ "T_LCD", "struct_t___l_c_d.html", "struct_t___l_c_d" ],
    [ "UG_AREA", "struct_u_g___a_r_e_a.html", "struct_u_g___a_r_e_a" ],
    [ "UG_BMP", "struct_u_g___b_m_p.html", "struct_u_g___b_m_p" ],
    [ "UG_BUTTON", "struct_u_g___b_u_t_t_o_n.html", "struct_u_g___b_u_t_t_o_n" ],
    [ "UG_CHECKBOX", "struct_u_g___c_h_e_c_k_b_o_x.html", "struct_u_g___c_h_e_c_k_b_o_x" ],
    [ "UG_DRIVER", "struct_u_g___d_r_i_v_e_r.html", "struct_u_g___d_r_i_v_e_r" ],
    [ "UG_FONT", "struct_u_g___f_o_n_t.html", "struct_u_g___f_o_n_t" ],
    [ "UG_GUI", "struct_u_g___g_u_i.html", "struct_u_g___g_u_i" ],
    [ "UG_IMAGE", "struct_u_g___i_m_a_g_e.html", "struct_u_g___i_m_a_g_e" ],
    [ "UG_MESSAGE", "struct_u_g___m_e_s_s_a_g_e.html", "struct_u_g___m_e_s_s_a_g_e" ],
    [ "UG_TEXT", "struct_u_g___t_e_x_t.html", "struct_u_g___t_e_x_t" ],
    [ "UG_TEXTBOX", "struct_u_g___t_e_x_t_b_o_x.html", "struct_u_g___t_e_x_t_b_o_x" ],
    [ "UG_TITLE", "struct_u_g___t_i_t_l_e.html", "struct_u_g___t_i_t_l_e" ],
    [ "UG_TOUCH", "struct_u_g___t_o_u_c_h.html", "struct_u_g___t_o_u_c_h" ]
];