var files_dup =
[
    [ "app.c", "app_8c.html", "app_8c" ],
    [ "app.h", "app_8h.html", "app_8h" ],
    [ "app_eventbus.c", "app__eventbus_8c.html", "app__eventbus_8c" ],
    [ "app_eventbus.h", "app__eventbus_8h.html", "app__eventbus_8h" ],
    [ "app_taskctrl.c", "app__taskctrl_8c.html", "app__taskctrl_8c" ],
    [ "app_taskctrl.h", "app__taskctrl_8h.html", "app__taskctrl_8h" ],
    [ "appDisp.c", "app_disp_8c.html", "app_disp_8c" ],
    [ "appDisp.h", "app_disp_8h.html", "app_disp_8h" ],
    [ "appInputs.c", "app_inputs_8c.html", "app_inputs_8c" ],
    [ "appInputs.h", "app_inputs_8h.html", "app_inputs_8h" ],
    [ "appReg.c", "app_reg_8c.html", "app_reg_8c" ],
    [ "appReg.h", "app_reg_8h.html", "app_reg_8h" ],
    [ "appTouch.c", "app_touch_8c.html", "app_touch_8c" ],
    [ "appTouch.h", "app_touch_8h.html", "app_touch_8h" ],
    [ "Display.c", "_display_8c.html", "_display_8c" ],
    [ "Display.h", "_display_8h.html", "_display_8h" ],
    [ "Driver_SR_SN74HCS596QPWRQ1.c", "_driver___s_r___s_n74_h_c_s596_q_p_w_r_q1_8c.html", null ],
    [ "Driver_SR_SN74HCS596QPWRQ1.h", "_driver___s_r___s_n74_h_c_s596_q_p_w_r_q1_8h.html", "_driver___s_r___s_n74_h_c_s596_q_p_w_r_q1_8h" ],
    [ "LCD_Driver.c", "_l_c_d___driver_8c.html", "_l_c_d___driver_8c" ],
    [ "LCD_Driver.h", "_l_c_d___driver_8h.html", "_l_c_d___driver_8h" ],
    [ "main.c", "main_8c.html", "main_8c" ],
    [ "Mc32_I2cUtilCCS.c", "_mc32___i2c_util_c_c_s_8c.html", "_mc32___i2c_util_c_c_s_8c" ],
    [ "Mc32_I2cUtilCCS.h", "_mc32___i2c_util_c_c_s_8h.html", "_mc32___i2c_util_c_c_s_8h" ],
    [ "PIC32130_AT42QT2120_I2C.c", "_p_i_c32130___a_t42_q_t2120___i2_c_8c.html", "_p_i_c32130___a_t42_q_t2120___i2_c_8c" ],
    [ "PIC32130_AT42QT2120_I2C.h", "_p_i_c32130___a_t42_q_t2120___i2_c_8h.html", "_p_i_c32130___a_t42_q_t2120___i2_c_8h" ],
    [ "ugui.c", "ugui_8c.html", "ugui_8c" ],
    [ "ugui.h", "ugui_8h.html", "ugui_8h" ],
    [ "ugui_config.h", "ugui__config_8h.html", "ugui__config_8h" ]
];