# cmake files support debug production
include("${CMAKE_CURRENT_LIST_DIR}/rule.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/file.cmake")

set(2414_DES_SP7_TestSprinkler_default_library_list )

# Handle files with suffix s, for group default-XC32
if(2414_DES_SP7_TestSprinkler_default_default_XC32_FILE_TYPE_assemble)
add_library(A_2414_DES_SP7_TestSprinkler_default_default_XC32_assemble OBJECT ${2414_DES_SP7_TestSprinkler_default_default_XC32_FILE_TYPE_assemble})
    A_2414_DES_SP7_TestSprinkler_default_default_XC32_assemble_rule(A_2414_DES_SP7_TestSprinkler_default_default_XC32_assemble)
    list(APPEND 2414_DES_SP7_TestSprinkler_default_library_list "$<TARGET_OBJECTS:A_2414_DES_SP7_TestSprinkler_default_default_XC32_assemble>")
endif()

# Handle files with suffix S, for group default-XC32
if(2414_DES_SP7_TestSprinkler_default_default_XC32_FILE_TYPE_assembleWithPreprocess)
add_library(A_2414_DES_SP7_TestSprinkler_default_default_XC32_assembleWithPreprocess OBJECT ${2414_DES_SP7_TestSprinkler_default_default_XC32_FILE_TYPE_assembleWithPreprocess})
    A_2414_DES_SP7_TestSprinkler_default_default_XC32_assembleWithPreprocess_rule(A_2414_DES_SP7_TestSprinkler_default_default_XC32_assembleWithPreprocess)
    list(APPEND 2414_DES_SP7_TestSprinkler_default_library_list "$<TARGET_OBJECTS:A_2414_DES_SP7_TestSprinkler_default_default_XC32_assembleWithPreprocess>")
endif()

# Handle files with suffix [cC], for group default-XC32
if(2414_DES_SP7_TestSprinkler_default_default_XC32_FILE_TYPE_compile)
add_library(A_2414_DES_SP7_TestSprinkler_default_default_XC32_compile OBJECT ${2414_DES_SP7_TestSprinkler_default_default_XC32_FILE_TYPE_compile})
    A_2414_DES_SP7_TestSprinkler_default_default_XC32_compile_rule(A_2414_DES_SP7_TestSprinkler_default_default_XC32_compile)
    list(APPEND 2414_DES_SP7_TestSprinkler_default_library_list "$<TARGET_OBJECTS:A_2414_DES_SP7_TestSprinkler_default_default_XC32_compile>")
endif()

# Handle files with suffix cpp, for group default-XC32
if(2414_DES_SP7_TestSprinkler_default_default_XC32_FILE_TYPE_compile_cpp)
add_library(A_2414_DES_SP7_TestSprinkler_default_default_XC32_compile_cpp OBJECT ${2414_DES_SP7_TestSprinkler_default_default_XC32_FILE_TYPE_compile_cpp})
    A_2414_DES_SP7_TestSprinkler_default_default_XC32_compile_cpp_rule(A_2414_DES_SP7_TestSprinkler_default_default_XC32_compile_cpp)
    list(APPEND 2414_DES_SP7_TestSprinkler_default_library_list "$<TARGET_OBJECTS:A_2414_DES_SP7_TestSprinkler_default_default_XC32_compile_cpp>")
endif()


add_executable(${2414_DES_SP7_TestSprinkler_default_image_name} ${2414_DES_SP7_TestSprinkler_default_library_list})
set_target_properties(${2414_DES_SP7_TestSprinkler_default_image_name} PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${2414_DES_SP7_TestSprinkler_default_output_dir})

target_link_libraries(${2414_DES_SP7_TestSprinkler_default_image_name} PRIVATE ${2414_DES_SP7_TestSprinkler_default_default_XC32_FILE_TYPE_link})

# Add the link options from the rule file.
A_2414_DES_SP7_TestSprinkler_default_link_rule(${2414_DES_SP7_TestSprinkler_default_image_name})

# Add bin2hex target for converting built file to a .hex file.
string(REGEX REPLACE [.]elf$ .hex 2414_DES_SP7_TestSprinkler_default_image_name_hex ${2414_DES_SP7_TestSprinkler_default_image_name})
add_custom_target(2414_DES_SP7_TestSprinkler_default_Bin2Hex ALL
    COMMAND ${MP_BIN2HEX} ${2414_DES_SP7_TestSprinkler_default_output_dir}/${2414_DES_SP7_TestSprinkler_default_image_name}
    BYPRODUCTS ${2414_DES_SP7_TestSprinkler_default_output_dir}/${2414_DES_SP7_TestSprinkler_default_image_name_hex}
    COMMENT Convert built file to .hex)
add_dependencies(2414_DES_SP7_TestSprinkler_default_Bin2Hex ${2414_DES_SP7_TestSprinkler_default_image_name})



